# Generated by Django 2.2 on 2021-08-14 23:57

from django.db import migrations, models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('clinic', jsonfield.fields.JSONField()),
                ('physician', jsonfield.fields.JSONField()),
                ('patient', jsonfield.fields.JSONField()),
                ('text', models.CharField(max_length=80)),
            ],
        ),
    ]
