# Generated by Django 2.2 on 2021-08-15 22:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptions',
            name='clinic',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='patient',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='physician',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
