version: "3.7"
networks:
  banco:
  back:

services:

  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./envs/postgres.env
    networks:
      - banco

  django:
    build:
      dockerfile: ./docker/dockerfile
      context: .
    command: python /source/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./source:/source
    env_file:
      - ./envs/postgres.env
      - .env
    environment:
      - DEBUG=True
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - banco
      - back
