name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: python:3.8-alpine
    strategy:
      max-parallel: 4
      matrix:
        python-version: 3.8

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv && pipenv install --system
    - name: Run Tests
      run: |
        ./load_envs.sh
        apk update
        apk add --no-cache build-base gcc libffi libffi-dev pcre-dev cairo cairo-dev linux-headers python3-dev postgresql-dev musl-dev jpeg-dev zlib-dev pango-dev gdk-pixbuf zlib git
        cd source
        coverage run --source='.' --omit=manage.py,iclinic/wsgi.py manage.py test
        coverage report -m --fail-under=80